### ISSUE TITLE
Option to easily delete files

### ISSUE THREAD

**Issue by zarevskaya** [aziis98/mup#3]
Hello, 

Do you plan to add an option to be able to directly delete files from the interface?

Thanks in advance.

**Comment by aziis98** [comment]
Nice suggestion, maybe I could add a delete button to each item in the recent uploads list

**Comment by zarevskaya** [comment]
Yes, that would make your app sexy! ;) Thanks aziis98!

**Comment by aziis98** [comment]
Done!

**Comment by zarevskaya** [comment]
Amazing! 
I can complete my article about your work!

https://belginux.com/installer-uploader-avec-docker/

This application is practical. THANKS.
